"""empty message

Revision ID: 15322ecb1a86
Revises: a56e8ca843ab
Create Date: 2022-05-05 16:53:45.012286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15322ecb1a86'
down_revision = 'a56e8ca843ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
